/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ilib;

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

import javax.swing.JPanel;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import com.mycompany.views.ClientBooks;
import com.mycompany.views.Login;

public class ClientDashboard extends javax.swing.JFrame {
        public ClientDashboard() {
                initComponents();
                InitStyles();
                SetDate();
                InitContent();
        }

        private void InitStyles() {
                mensaje.putClientProperty("FlatLaf.style", "font: 14 $light.font");
                mensaje.setForeground(Color.black);
                navText.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
                navText.setForeground(Color.white);
                dateText.putClientProperty("FlatLaf.style", "font: 24 $light.font");
                dateText.setForeground(Color.white);
                appName.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
                appName.setForeground(Color.white);
        }

        private void SetDate() {
                LocalDate now = LocalDate.now();
                Locale spanishLocale = new Locale("es", "ES");
                dateText.setText(
                                now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy",
                                                spanishLocale)));
        }

        private void InitContent() {
                ShowJPanel(new Login());
                HideLoggedInButtons();
        }

        private static void HideLoggedInButtons() {
                btn_logout.setVisible(false);
                btn_books.setVisible(false);
                btn_lend.setVisible(false);
                btn_login.setVisible(true);
        }

        private static void ShowLoggedInButtons() {
                btn_logout.setVisible(true);
                btn_books.setVisible(true);
                btn_lend.setVisible(true);
                btn_login.setVisible(false);
        }

        public static void ShowJPanel(JPanel p) {
                if (ClientSession.getInstance().getUserId() != -1) {
                        ShowLoggedInButtons();
                } else {
                        HideLoggedInButtons();
                }

                p.setSize(850, 430);
                p.setLocation(0, 0);

                content.removeAll();
                content.add(p, BorderLayout.CENTER);
                content.revalidate();
                content.repaint();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                background = new javax.swing.JPanel();
                menu = new javax.swing.JPanel();
                appName = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                btn_login = new javax.swing.JButton();
                btn_books = new javax.swing.JButton();
                btn_lend = new javax.swing.JButton();
                btn_logout = new javax.swing.JButton();
                header = new javax.swing.JPanel();
                navText = new javax.swing.JLabel();
                dateText = new javax.swing.JLabel();
                content = new javax.swing.JPanel();
                mensaje = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(1050, 660));

                background.setBackground(new java.awt.Color(255, 255, 255));

                menu.setBackground(new java.awt.Color(13, 71, 161));
                menu.setPreferredSize(new java.awt.Dimension(270, 640));

                appName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                appName.setText("iLib");

                jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

                btn_login.setBackground(new java.awt.Color(21, 101, 192));
                btn_login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btn_login.setForeground(new java.awt.Color(255, 255, 255));
                btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-outline.png"))); // NOI18N
                btn_login.setText("Inicio de Sesión");
                btn_login.setBorder(
                                javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
                btn_login.setBorderPainted(false);
                btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                btn_login.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btn_login.setIconTextGap(13);
                btn_login.setInheritsPopupMenu(true);
                btn_login.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_loginActionPerformed(evt);
                        }
                });

                btn_books.setBackground(new java.awt.Color(21, 101, 192));
                btn_books.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btn_books.setForeground(new java.awt.Color(255, 255, 255));
                btn_books.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar-plus.png"))); // NOI18N
                btn_books.setText("Mis libros");
                btn_books.setBorder(
                                javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
                btn_books.setBorderPainted(false);
                btn_books.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                btn_books.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btn_books.setIconTextGap(13);
                btn_books.setInheritsPopupMenu(true);
                btn_books.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_booksActionPerformed(evt);
                        }
                });

                btn_lend.setBackground(new java.awt.Color(21, 101, 192));
                btn_lend.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btn_lend.setForeground(new java.awt.Color(255, 255, 255));
                btn_lend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar-multiple-check.png"))); // NOI18N
                btn_lend.setText("Reservar");
                btn_lend.setBorder(
                                javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
                btn_lend.setBorderPainted(false);
                btn_lend.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                btn_lend.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btn_lend.setIconTextGap(13);
                btn_lend.setInheritsPopupMenu(true);
                btn_lend.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_lendActionPerformed(evt);
                        }
                });

                btn_logout.setBackground(new java.awt.Color(21, 101, 192));
                btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btn_logout.setForeground(new java.awt.Color(255, 255, 255));
                btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file-chart.png"))); // NOI18N
                btn_logout.setText("Cerrar sesión");
                btn_logout.setBorder(
                                javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
                btn_logout.setBorderPainted(false);
                btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                btn_logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btn_logout.setIconTextGap(13);
                btn_logout.setInheritsPopupMenu(true);
                btn_logout.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_logoutActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
                menu.setLayout(menuLayout);
                menuLayout.setHorizontalGroup(
                                menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(menuLayout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(appName,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                250,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(menuLayout.createSequentialGroup()
                                                                .addGap(40, 40, 40)
                                                                .addComponent(jSeparator1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                190,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(btn_lend, javax.swing.GroupLayout.PREFERRED_SIZE, 270,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 270,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_books, javax.swing.GroupLayout.PREFERRED_SIZE, 270,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 270,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                menuLayout.setVerticalGroup(
                                menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(menuLayout.createSequentialGroup()
                                                                .addGap(52, 52, 52)
                                                                .addComponent(appName,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                34,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(4, 4, 4)
                                                                .addComponent(jSeparator1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                20,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(20, 20, 20)
                                                                .addGroup(menuLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(menuLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(100, 100, 100)
                                                                                                .addComponent(btn_lend,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                52,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(btn_logout,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                52,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(menuLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(50, 50, 50)
                                                                                                .addComponent(btn_books,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                52,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(btn_login,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                52,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))));

                header.setBackground(new java.awt.Color(25, 118, 210));
                header.setPreferredSize(new java.awt.Dimension(744, 150));

                navText.setText("Cliente/Control/Biblioteca");

                dateText.setText("Hoy es {dayname} {day} de {month} de {year}");

                javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
                header.setLayout(headerLayout);
                headerLayout.setHorizontalGroup(
                                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(headerLayout.createSequentialGroup()
                                                                .addGap(66, 66, 66)
                                                                .addGroup(headerLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(navText,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(dateText,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                434,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(260, Short.MAX_VALUE)));
                headerLayout.setVerticalGroup(
                                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(headerLayout.createSequentialGroup()
                                                                .addGap(33, 33, 33)
                                                                .addComponent(navText,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                33,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(dateText,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(31, Short.MAX_VALUE)));

                content.setBackground(new java.awt.Color(255, 255, 255));
                content.setLayout(new java.awt.BorderLayout());

                mensaje.setText("We ♥  the reading!");

                javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
                background.setLayout(backgroundLayout);
                backgroundLayout.setHorizontalGroup(
                                backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(backgroundLayout.createSequentialGroup()
                                                                .addComponent(menu,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(
                                                                                backgroundLayout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(backgroundLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(10, 10, 10)
                                                                                                                .addComponent(mensaje,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                389,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addComponent(header,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                760,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(content,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))));
                backgroundLayout.setVerticalGroup(
                                backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                .addGroup(backgroundLayout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addComponent(mensaje,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                26,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(header,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(content,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(1, 1, 1)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_logoutActionPerformed
                HideLoggedInButtons();
                ShowJPanel(new Login());
                javax.swing.JOptionPane.showMessageDialog(this, "Sesión cerrada con éxito. \n",
                                "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }// GEN-LAST:event_btn_logoutActionPerformed

        private void btn_lendActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_lendActionPerformed
                ShowJPanel(new ClientBooks(true));
        }// GEN-LAST:event_btn_lendActionPerformed

        private void btn_booksActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_booksActionPerformed
                ShowJPanel(new ClientBooks(false));
        }// GEN-LAST:event_btn_booksActionPerformed

        private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_loginActionPerformed
                ShowJPanel(new Login());
        }// GEN-LAST:event_btn_loginActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                FlatMaterialLighterIJTheme.setup();

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new ClientDashboard().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel appName;
        private javax.swing.JPanel background;
        private static javax.swing.JButton btn_books;
        private static javax.swing.JButton btn_lend;
        private static javax.swing.JButton btn_login;
        private static javax.swing.JButton btn_logout;
        private static javax.swing.JPanel content;
        private javax.swing.JLabel dateText;
        private javax.swing.JPanel header;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JLabel mensaje;
        private javax.swing.JPanel menu;
        private javax.swing.JLabel navText;
        // End of variables declaration//GEN-END:variables
}
